---
   - name: install nginx
     apt: name=nginx update_cache=yes state=present

   - name: copy default file
     template: src=default dest=/etc/nginx/templates/default

   - name: nginx start
     service: name=nginx state=started

   - name: nginx restart
     service: name=nginx state=restarted
 


